name: Build tutorial

concurrency:
  group: tutorial-publish
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    name: Build tutorial
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm install
      - run: npx quartz build
      - run: cp ./vercel.json ./public/vercel.json

      - name: Push to AuroraDysis/TutorialStatic
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: AuroraDysis/TutorialStatic
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          publish_dir: ./public
          publish_branch: main
          commit_message: "Update pages"
